# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 818f478a4b22da921750e8968d1cbe029e83405a1c40ca840141d45fff0cc4d2799b5b36e4292c521baa9286ea8b8c8d8a323cae6d9a0b82adfbee12c245d14b

test:
  secret_key_base: 4e029076388b006ecfcbb79ce3a67079ff4c6e580d5257df73c412f18f319c0f9c282b442493873c76dc28f0c907563fbbe182f123d981dc7b7aa89836d90722

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
