# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8be08302714a45ac594a5222429bcc5ba78084888ec8a3e40265dc0e99724ee1cca81d1c1b72b05f5f33f958d1ae14809a6608cb338e41e07f74ea146b9d3952

test:
  secret_key_base: 553f05478bc42071f0064c40cab6a0c59f22fc9ed889579980355dd61fa56dc5e4393e30cb1d8ce1f1088b0751231a8bd6413b1f057e1fd063b8c2d394c2e15e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
